cd bitcointranscripts || exit
git checkout "${3}-${1}"
# add the transcript to the repo and commit
git add . && git commit -m "added ${4}"
git push origin "${3}-${1}"

echo "Setting default repo to ${2}/bitcointranscripts"
# set the default repo to the fork
gh repo set-default "${2}"/bitcointranscripts

# push the changes to the fork and create a pull request
gh pr create --base master --title "Autogenerated ${4} by tstbtc" --body "transcribed to bitcoin transcript for ${4}" --head "${2}:${3}-${1}"

echo "Done"

